import {createModel,buildGeometry,pathFor,color,label,list,parseFiles,filterEvents} from './core.mjs';
const $=s=>document.querySelector(s), el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;},ns='http://www.w3.org/2000/svg';
const svg=(tag,attrs={})=>{const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e;};
const icons={panel:'M4 4h16v16H4z M9 4v16',search:'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',filter:'M4 7h16 M4 17h16 M9 4v6 M15 14v6',calendar:'M4 5h16v15H4z M4 10h16 M8 3v4 M16 3v4',minus:'M5 12h14',plus:'M5 12h14 M12 5v14',fit:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',close:'M6 6l12 12 M18 6L6 18',refresh:'M20 8a8 8 0 1 0 0 8 M20 3v5h-5',list:'M8 5h12 M8 12h12 M8 19h12 M3 5h1 M3 12h1 M3 19h1',database:'M4 6c0-4 16-4 16 0v12c0 4-16 4-16 0z M4 6c0 4 16 4 16 0 M4 12c0 4 16 4 16 0'};
document.querySelectorAll('[data-icon]').forEach(e=>{const s=svg('svg',{viewBox:'0 0 24 24'});s.append(svg('path',{d:icons[e.dataset.icon]||icons.list}));e.append(s);});
let model,config,events=[],geometry,paths=[],range=[0,1],full=[0,1],selected=new Set(),filters={},drag=null,renderPending=false;
const mobile=()=>innerWidth<=760, reduced=matchMedia('(prefers-reduced-motion: reduce)');
const fmt=d=>{if(d==null)return 'Без точної дати';const a=model.dateAt(d);return `${a.day}.${String(a.month).padStart(2,'0')} · рік ${a.year}`;};
const name=id=>label(model.entities.get(id))||id;
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4500);}
function showDialog(id){document.body.classList.remove('sidebar-open');const d=$('#'+id);if(!d.open)d.showModal();}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).close();const a=e.target.closest('[data-action]')?.dataset.action;if(a==='sidebar')document.body.classList.toggle(mobile()?'sidebar-open':'sidebar-collapsed');if(a==='search'){showDialog('search-dialog');search();$('#search-input').focus();}if(a==='filters')showDialog('filter-dialog');if(a==='records')records();if(a==='source')source();if(a==='help')help();});
function detail(title,eyebrow='Подія'){ $('#detail-content').replaceChildren();$('#detail-eyebrow').textContent=eyebrow;$('#detail-content').append(el('h2','',title));showDialog('detail-dialog');return $('#detail-content');}
function raw(parent,value,title='Усі поля запису'){const d=el('details','raw-data');d.append(el('summary','',title),el('pre','',typeof value==='string'?value:JSON.stringify(value,null,2)));parent.append(d);}
function eventButton(e,parent){const b=el('button','record-button');b.append(el('strong','',e.title||e.id),el('small','',fmt(e.day)));b.onclick=()=>openEvent(e);parent.append(b);}
function people(parent,title,ids,active=false){if(!ids.size)return;parent.append(el('h3','',title));const p=el('div','people-chips');for(const id of ids){const b=el('button','person-chip'+(active?' active':''));b.style.setProperty('--char',color(id));b.append(el('i'),document.createTextNode(name(id)));b.onclick=()=>{const q=detail(name(id),'Персонаж');model.events.filter(x=>x.physical.has(id)||x.mentioned.has(id)).forEach(x=>eventButton(x,q));raw(q,model.entities.get(id));};p.append(b);}parent.append(p);}
function openEvent(e){const p=detail(e.title||e.id);const meta=el('div','detail-meta');meta.append(el('span','',fmt(e.day)));if(e.origin)meta.append(el('span','origin',e.origin));p.append(meta);if(e.text)p.append(el('p','event-text',e.text));people(p,'Учасники',e.active,true);people(p,'Фізично присутні',new Set([...e.physical].filter(x=>!e.active.has(x))));people(p,'Згадані',e.mentioned);if(e.scene.location_id)p.append(el('h3','','Місце'),el('p','detail-place',name(e.scene.location_id)));if(e.uncertain)p.append(el('p','uncertainty','Частина порядку всередині дня не встановлена. Положення вузлів не означає точного часу або одночасності.'));const jump=el('button','soft-button','Показати на стрічці');jump.onclick=()=>{if(e.day!=null){range=[e.day-.05,e.day+1.05];render();}$('#detail-dialog').close();};p.append(jump);const rel=model.relations.filter(r=>[e.id,e.scene.id].includes(r.a)||[e.id,e.scene.id].includes(r.b));if(rel.length){p.append(el('h3','','Зв’язки'));for(const r of rel){const id=[e.id,e.scene.id].includes(r.a)?r.b:r.a;const b=el('button','record-button');b.append(el('strong','',model.records.get(id)?.title||id),el('small','',r.kind));b.onclick=()=>{const v=model.records.get(id);if(v?.scene)openEvent(v);else{const q=detail(v?.title||id,'Сцена');list(v?.events).forEach(x=>eventButton(model.records.get(x.id),q));raw(q,v||r);}};p.append(b);}}
if(e.evidence_ids?.length){p.append(el('h3','','Джерела'));for(const id of e.evidence_ids){const ev=model.evidence.get(id),s=model.sources.get(ev?.source_id);const c=el('div','source-card');c.append(el('strong','',s?.title||id));if(ev?.locator)c.append(el('p','',ev.locator));raw(c,{evidence:ev,source:s},'Деталі джерела');p.append(c);}}
raw(p,Object.fromEntries(Object.entries(e).filter(([k])=>!['scene','physical','active','mentioned','rank','early','late','position','uncertain','day'].includes(k))));raw(p,model.bundle.documents[e.scene.file],'Повна сцена');}
function records(){const p=detail('Усі записи','Хронологія');model.events.forEach(e=>eventButton(e,p));if(model.pending.length){p.append(el('h3','',`Очікують міграції · ${model.pending.length}`));for(const r of model.pending){const b=el('button','record-button');b.append(el('strong','',r.original?.Event||r.legacy_id),el('small','',r.original?.Date||''));b.onclick=()=>{const q=detail(r.original?.Title||r.legacy_id,'Запис до міграції');q.append(el('p','event-text',r.original?.Event));raw(q,r);};p.append(b);}}}
function source(){const p=detail('Дані хронології');p.append(el('p','detail-place',`${model.events.length} подій · ${model.scenes.length} сцен · ${model.entities.size} сутностей`));for(const [path,text]of Object.entries(model.bundle.raw||{}))raw(p,text,path);}
function help(){const p=detail('Як читати стрічку');for(const t of ['Кожна кольорова нитка — окремий персонаж. Наближення розкриває щільний пучок.','Натисніть вузол, щоб відкрити подію. Число у вузлі означає кілька близьких записів.','Лінії між сценами показують зв’язок появ персонажа, а не безперервну фізичну присутність.','Невідомий порядок лишається невідомим. Подробиці часових зв’язків доступні в картці.'])p.append(el('p','event-text',t));}
function search(){const q=$('#search-input').value.toLowerCase().trim(),p=$('#search-results');p.replaceChildren();const results=model.events.filter(e=>!q||`${e.title} ${e.text} ${[...e.physical,...e.mentioned].map(name).join(' ')} ${name(e.scene.location_id)}`.toLowerCase().includes(q));for(const e of results){const b=el('button','search-result');b.append(el('strong','',e.title||e.id),el('small','',fmt(e.day)));b.onclick=()=>{$('#search-dialog').close();openEvent(e);};p.append(b);}if(!results.length)p.append(el('div','empty-result','Нічого не знайдено'));}
$('#search-input').oninput=search;
function characters(){const p=$('#characters');p.replaceChildren();const q=$('#character-search').value.toLowerCase();const ids=[...new Set(model.events.flatMap(e=>[...e.physical,...e.mentioned]))].sort((a,b)=>name(a).localeCompare(name(b),'uk'));for(const id of ids){if(!name(id).toLowerCase().includes(q))continue;const b=el('button','character');b.setAttribute('aria-pressed',selected.has(id));b.style.setProperty('--char',color(id));b.append(el('i','swatch'),el('span','character-name',name(id)),el('small','',model.events.filter(e=>e.physical.has(id)).length));b.onclick=()=>{selected.has(id)?selected.delete(id):selected.add(id);applyFilters();characters();};p.append(b);}}
$('#character-search').oninput=characters;$('#clear-selection').onclick=()=>{selected.clear();characters();applyFilters();};
function options(selector,values,all){const s=$(selector),old=s.value;s.replaceChildren();if(all)s.append(new Option(all,''));values.forEach(([id,name])=>s.append(new Option(name,id)));if([...s.options].some(o=>o.value===old))s.value=old;}
function install(bundle,preserve=false){const next=createModel(bundle);model=next;const days=[...model.days.keys()].sort((a,b)=>a-b);full=days.length?[days[0]-.5,days.at(-1)+1.5]:[0,1];if(!preserve)range=[...full];options('#continuity',[...new Set(model.scenes.map(s=>s.continuity_id))].map(x=>[x,x]));options('#filter-team',[...model.entities.values()].filter(x=>x.kind==='team').map(x=>[x.id,label(x)]),'Усі команди');options('#filter-origin',[...new Set(model.events.map(e=>e.origin).filter(Boolean))].sort().map(x=>[x,x]),'Усі');options('#filter-location',[...model.entities.values()].filter(x=>x.kind==='location').map(x=>[x.id,label(x)]),'Усі місця');options('#filter-source',[...model.sources.values()].map(x=>[x.id,x.title||x.id]),'Усі джерела');$('#period').replaceChildren(new Option('Увесь період','all'),...days.map(d=>new Option(fmt(d),d)));$('#record-count').textContent=model.events.length+model.pending.length;$('#source-caption').textContent=`${Object.keys(bundle.raw||{}).length} файлів даних`;$('#sync-status').textContent='Дані завантажено';characters();applyFilters();}
function applyFilters(){filters={continuity:$('#continuity').value,entities:[...selected],team:$('#filter-team').value,origin:$('#filter-origin').value,location:$('#filter-location').value,source:$('#filter-source').value};events=filterEvents(model,filters);const count=selected.size+['team','origin','location','source'].filter(k=>filters[k]).length;$('#filter-count').hidden=!count;$('#filter-count').textContent=count;render();}
['#continuity','#filter-team','#filter-origin','#filter-location','#filter-source','#filter-mode'].forEach(s=>$(s).onchange=applyFilters);
$('#reset-filters').onclick=()=>{selected.clear();['#filter-team','#filter-origin','#filter-location','#filter-source'].forEach(s=>$(s).value='');characters();applyFilters();};
$('#period').onchange=()=>{range=$('#period').value==='all'?[...full]:[+$('#period').value-.05,+$('#period').value+1.05];render();};
function schedule(){if(!renderPending){renderPending=true;requestAnimationFrame(()=>{renderPending=false;render();});}}
function zoom(factor,at=.5){const width=range[1]-range[0],newWidth=Math.min(full[1]-full[0],Math.max(.04,width/factor));const anchor=range[0]+width*at;range=[anchor-newWidth*at,anchor+newWidth*(1-at)];clamp();schedule();}
function clamp(){const w=range[1]-range[0];if(range[0]<full[0])range=[full[0],full[0]+w];if(range[1]>full[1])range=[full[1]-w,full[1]];}
$('#zoom-in').onclick=()=>zoom(1.8);$('#zoom-out').onclick=()=>zoom(1/1.8);$('#fit').onclick=$('#zoom-value').onclick=()=>{range=[...full];$('#period').value='all';render();};
function render(){if(!model)return;const viewport=$('#viewport'),rect=viewport.getBoundingClientRect(),vertical=mobile(),span=vertical?rect.height:rect.width,cross=vertical?rect.width:rect.height,z=(full[1]-full[0])/(range[1]-range[0]);geometry=buildGeometry(model,events,{start:range[0],end:range[1],span,cross,zoom:z,vertical,only:$('#filter-mode').value==='only'?selected:new Set()});$('#timeline').setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);$('#threads').replaceChildren();$('#nodes').replaceChildren();$('#axis').replaceChildren();paths=[];
for(const s of geometry.segments){const p=svg('path',{d:pathFor(s,0,vertical),stroke:color(s.id),'stroke-width':z<2?1.7:2,'class':'thread',opacity:s.continuity?.55:.86});$('#threads').append(p);paths.push([p,s]);}
for(const c of geometry.clusters){const x=vertical?c.y:c.x,y=vertical?c.x:c.y,many=c.items.length>1;const g=svg('g',{transform:`translate(${x} ${y})`,class:'event-node',tabindex:'0',role:'button','aria-label':many?`${c.items.length} подій`:c.items[0].event.title});g.append(svg('circle',{r:20,class:'target'}),svg('circle',{r:many?10:4.2,class:'node-disc'}));if(many){const t=svg('text',{class:'node-count'});t.textContent=c.items.length;g.append(t);}const open=()=>{if(drag?.moved)return;if(!many)openEvent(c.items[0].event);else{const p=detail(`${c.items.length} подій`,'Події поруч');const b=el('button','soft-button','Наблизити');b.onclick=()=>{const ds=c.items.map(i=>i.event.day);range=[Math.min(...ds)-.04,Math.max(...ds)+1.04];$('#detail-dialog').close();render();};p.append(b);c.items.forEach(i=>eventButton(i.event,p));}};g.onclick=open;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};g.onpointerenter=()=>{if(vertical||drag)return;const t=$('#tooltip');t.replaceChildren();t.append(el('small','',fmt(c.items[0].event.day)),el('h3','',many?`${c.items.length} подій`:c.items[0].event.title),el('p','',many?c.items.slice(0,3).map(i=>i.event.title).join(' · '):c.items[0].event.text));t.hidden=false;t.style.left=Math.max(8,Math.min(rect.width-330,x+15))+'px';t.style.top=Math.max(8,Math.min(rect.height-t.offsetHeight-8,y+18))+'px';};g.onpointerleave=()=>$('#tooltip').hidden=true;$('#nodes').append(g);}
const step=(range[1]-range[0])>65?30:(range[1]-range[0])>18?7:(range[1]-range[0])>6?2:1;let last=-1000;for(let d=Math.ceil(range[0]);d<=range[1];d++){if(d%step)continue;const t=(d-range[0])/(range[1]-range[0])*span;if(t-last<(vertical?48:88))continue;last=t;const text=svg('text',{x:vertical?10:t,y:vertical?t:cross/2-Math.min(geometry.detail*145+38,cross/2-25),class:'axis-label','text-anchor':vertical?'start':'middle'});const dt=model.dateAt(d);text.textContent=`${dt.day}.${String(dt.month).padStart(2,'0')}`;$('#axis').append(text);}
$('#range-title').textContent=Math.floor(range[0])===Math.floor(range[1])?fmt(range[0]):`${fmt(Math.max(range[0],full[0]+.5))} — ${fmt(Math.min(range[1],full[1]-1.5))}`;$('#range-meta').textContent=`${events.length} подій · ${geometry.ids.length} персонажів`;$('#visible-caption').textContent=`У вікні: ${geometry.visible.length}`;$('#zoom-value').textContent=`${Math.round(z*100)}%`;$('#canvas-message').hidden=geometry.visible.length>0;$('#canvas-message').textContent=events.length?'У цьому проміжку немає подій':'Немає подій за цими фільтрами';minimap();}
function minimap(){const vertical=mobile(),r=$('#minimap').getBoundingClientRect(),s=$('#mini-svg');s.replaceChildren();s.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);for(const e of events){if(e.day==null)continue;const t=(e.position-full[0])/(full[1]-full[0])*(vertical?r.height:r.width);const line=svg('line',{x1:vertical?4:t,x2:vertical?r.width-4:t,y1:vertical?t:7,y2:vertical?t:r.height-7,stroke:color([...e.physical][0]||e.id),'stroke-width':2});s.append(line);}const win=$('#mini-window'),a=(range[0]-full[0])/(full[1]-full[0])*100,b=(range[1]-range[0])/(full[1]-full[0])*100;win.style.cssText=vertical?`top:${a}%;height:${b}%;left:2px;right:2px`:`left:${a}%;width:${b}%;top:2px;bottom:2px`;}
const vp=$('#viewport'),touches=new Map();vp.onwheel=e=>{e.preventDefault();const r=vp.getBoundingClientRect(),at=mobile()?(e.clientY-r.top)/r.height:(e.clientX-r.left)/r.width;zoom(Math.exp(-e.deltaY*.002),at);};
vp.onpointerdown=e=>{touches.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={last:mobile()?e.clientY:e.clientX,moved:false,start:e.clientX+e.clientY};if(!e.target.closest('.event-node'))vp.setPointerCapture(e.pointerId);vp.classList.add('dragging');$('#tooltip').hidden=true;};
vp.onpointermove=e=>{if(!touches.has(e.pointerId))return;const old=[...touches.values()];touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const now=[...touches.values()],dist=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);zoom(dist(now)/Math.max(1,dist(old)));drag.moved=true;return;}const pos=mobile()?e.clientY:e.clientX;if(Math.abs(e.clientX+e.clientY-drag.start)>5)drag.moved=true;const r=vp.getBoundingClientRect(),delta=(pos-drag.last)/(mobile()?r.height:r.width)*(range[1]-range[0]);range=range.map(x=>x-delta);drag.last=pos;clamp();schedule();};
function endPointer(e){touches.delete(e.pointerId);vp.classList.remove('dragging');setTimeout(()=>{if(!touches.size)drag=null;},0);}vp.onpointerup=endPointer;vp.onpointercancel=endPointer;
vp.onkeydown=e=>{if(e.target.closest('.event-node'))return;if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))e.preventDefault();if(['+','='].includes(e.key))zoom(1.5);if(e.key==='-')zoom(1/1.5);if(e.key==='Home')$('#fit').click();if(e.key.startsWith('Arrow')){const d=(range[1]-range[0])*.15*(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);range=range.map(x=>x+d);clamp();render();}};
let miniDrag=false;function miniMove(e){if(!miniDrag)return;const r=$('#minimap').getBoundingClientRect(),ratio=mobile()?(e.clientY-r.top)/r.height:(e.clientX-r.left)/r.width,w=range[1]-range[0],center=full[0]+ratio*(full[1]-full[0]);range=[center-w/2,center+w/2];clamp();schedule();}$('#minimap').onpointerdown=e=>{miniDrag=true;e.currentTarget.setPointerCapture(e.pointerId);miniMove(e);};$('#minimap').onpointermove=miniMove;$('#minimap').onpointerup=()=>miniDrag=false;
new ResizeObserver(schedule).observe(vp);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();showDialog('search-dialog');search();$('#search-input').focus();}});
let previous=0;function animate(t){if(!reduced.matches&&!document.hidden&&t-previous>45){for(const [p,s]of paths)p.setAttribute('d',pathFor(s,t,mobile()));previous=t;}requestAnimationFrame(animate);}requestAnimationFrame(animate);
async function refresh(manual=false){if(!config||$('#refresh').disabled)return;$('#refresh').disabled=true;$('#refresh').classList.add('spinning');try{const response=await fetch(`https://api.github.com/repos/${config.repository}/git/trees/${config.ref}?recursive=1`);if(!response.ok)throw Error(`HTTP ${response.status}`);const tree=await response.json();if(tree.truncated)throw Error('Неповний список файлів');if(tree.sha===model.bundle.revision){$('#sync-status').textContent='Дані актуальні';return;}const files=tree.tree.filter(f=>f.type==='blob'&&f.path.startsWith(config.directory));const raw={};let cursor=0;await Promise.all(Array.from({length:4},async()=>{while(cursor<files.length){const f=files[cursor++],res=await fetch(`https://raw.githubusercontent.com/${config.repository}/${tree.sha}/${f.path}`);if(!res.ok)throw Error(f.path);raw[f.path.slice(config.directory.length)]=await res.text();}}));const bundle={...parseFiles(raw,window.jsyaml.load),revision:tree.sha,schema_version:1};install(bundle,true);try{localStorage.setItem('timeline-cache',JSON.stringify(bundle));}catch{}$('#sync-status').textContent='Оновлено з джерела';if(manual)toast('Хронологію оновлено');}catch(e){$('#sync-status').textContent='Збережена версія';if(manual)toast('Оновлення недоступне. Збережена версія лишається доступною.');console.warn('Data refresh:',e.message);}finally{$('#refresh').disabled=false;$('#refresh').classList.remove('spinning');}}
$('#refresh').onclick=()=>refresh(true);
try{const [bundle,c]=await Promise.all([fetch('./timeline-data.json').then(r=>r.json()),fetch('./source-config.json').then(r=>r.json())]);config=c;let cached;try{cached=JSON.parse(localStorage.getItem('timeline-cache'));}catch{}install(cached?.documents?cached:bundle);if(config.automaticUpdate)refresh();}catch(error){$('#canvas-message').hidden=false;$('#canvas-message').textContent=`Не вдалося прочитати дані: ${error.message}`;$('#sync-status').textContent='Помилка читання';console.error(error);}
